language: rust

# upload takes too long on windows and gets killed due to inactivity
#cache: cargo

matrix:
  include:
  - os: linux
    rust: stable
    env:
    - BUILD_MODE=test
  - os: linux
    rust: stable
    env:
    - BUILD_MODE=common
  - os: linux
    rust: stable
    env:
    - BUILD_MODE=std
  - os: linux
    rust: stable
    env:
    - BUILD_MODE=boxxy

before_install:
- ci/setup.sh "$TRAVIS_OS_NAME"
script:
- df -h
- ci/run.sh $BUILD_MODE
- df -h

notifications:
  irc:
    template:
    - "%{repository_slug}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (%{build_url})"
    channels:
    - "ircs://irc.hackint.org:6697/#sn0int"
    use_notice: true
    skip_join: true
    #on_success: change # default: always
    #on_failure: always # default: always
